package com.glancy.backend.dto;

import com.glancy.backend.entity.Language;
import java.time.LocalDateTime;

/**
 * Detailed representation of a single search result version.
 *
 * @param id unique identifier of the version entity.
 * @param searchRecordId identifier of the owning search record.
 * @param wordId optional identifier of the associated cached word.
 * @param userId identifier of the user who triggered the version.
 * @param term search term associated with this version.
 * @param language language context used for the lookup.
 * @param model language model that produced the version content.
 * @param versionNumber sequential number within the search record history.
 * @param content full persisted content as generated by the model.
 * @param preview truncated preview text for quick scanning.
 * @param createdAt timestamp indicating when this version was captured.
 */
public record SearchResultVersionResponse(
    Long id,
    Long searchRecordId,
    Long wordId,
    Long userId,
    String term,
    Language language,
    String model,
    Long versionNumber,
    String content,
    String preview,
    LocalDateTime createdAt
) {}
