spring:
  application:
    name: glancy
  messages:
    basename: i18n/messages
  mail:
    host: localhost
    port: 1025
  datasource:
    url: jdbc:mysql://localhost:3306/glancy_db?useSSL=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: glancy_user
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        "[format_sql]": true
  web:
    resources:
      add-mappings: false
  config:
    import:
      - classpath:config/search.yml
      - classpath:config/llm.yml
      - classpath:config/thirdparty.yml
      - classpath:config/oss.yml
      - classpath:config/tts.yml
logging:
  config: classpath:/config/logback-spring.xml
management:
  endpoints:
    web:
      exposure:
        include: health,info
  logging:
    level:
      "[org.springframework.security]": DEBUG
      "[com.glancy.backend]": DEBUG
      "[org.springframework.web]": INFO
