-- Database schema for Glancy Backend
CREATE TABLE IF NOT EXISTS users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(100) UNIQUE,
  avatar VARCHAR(255),
  phone VARCHAR(30),
  deleted BOOLEAN NOT NULL DEFAULT FALSE,
  member BOOLEAN NOT NULL DEFAULT FALSE,
  createdAt DATETIME (6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updatedAt DATETIME (6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  lastLoginAt DATETIME,
  loginToken VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS search_records (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  term VARCHAR(100) NOT NULL,
  language VARCHAR(10) NOT NULL,
  flavor VARCHAR(32) NOT NULL DEFAULT 'BILINGUAL',
  deleted BOOLEAN NOT NULL DEFAULT FALSE,
  createdAt DATETIME (6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updatedAt DATETIME (6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_search_record_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS words (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  term VARCHAR(100) NOT NULL,
  normalized_term VARCHAR(120) NOT NULL,
  language VARCHAR(10) NOT NULL,
  flavor VARCHAR(32) NOT NULL,
  phonetic VARCHAR(100),
  example VARCHAR(255),
  markdown TEXT,
  deleted BOOLEAN NOT NULL DEFAULT FALSE,
  createdAt DATETIME (6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updatedAt DATETIME (6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT uk_words_term_language_flavor UNIQUE (term, language, flavor),
  CONSTRAINT uk_words_normalized_language_flavor UNIQUE (normalized_term, language, flavor)
);

CREATE TABLE IF NOT EXISTS word_issue_reports (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  term VARCHAR(120) NOT NULL,
  language VARCHAR(16) NOT NULL,
  flavor VARCHAR(32) NOT NULL,
  issue_category VARCHAR(40) NOT NULL,
  description TEXT,
  source_url VARCHAR(500),
  report_user_id BIGINT,
  deleted BOOLEAN NOT NULL DEFAULT FALSE,
  createdAt DATETIME (6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updatedAt DATETIME (6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS word_definitions (
  word_id BIGINT NOT NULL,
  definition TEXT NOT NULL,
  PRIMARY KEY (word_id, definition),
  CONSTRAINT fk_word_definition_word FOREIGN KEY (word_id) REFERENCES words (id)
);

CREATE TABLE IF NOT EXISTS third_party_accounts (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  provider VARCHAR(50) NOT NULL,
  externalId VARCHAR(100) NOT NULL,
  CONSTRAINT fk_third_party_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS login_devices (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  deviceInfo VARCHAR(255) NOT NULL,
  loginTime DATETIME NOT NULL,
  CONSTRAINT fk_login_device_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS alert_recipients (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS traffic_records (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  path VARCHAR(100) NOT NULL,
  ip VARCHAR(45),
  userAgent VARCHAR(255),
  createdAt DATETIME (6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS system_parameters (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE,
  value VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS user_keyboard_shortcuts (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  action VARCHAR(40) NOT NULL,
  binding VARCHAR(120) NOT NULL,
  CONSTRAINT fk_user_shortcut_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT uk_user_action UNIQUE (user_id, action),
  CONSTRAINT uk_user_binding UNIQUE (user_id, binding)
);
