name: 部署到云服务器

on:
  push:
    branches:
      - main
      - 'feature-*'

jobs:
  build_and_deploy:
    name: 构建并部署
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: 安装依赖
        run: npm ci
        working-directory: glancy-site
      - name: 代码检查
        run: |
          npm run lint
          npm run lint:css
        working-directory: glancy-site
      - name: 构建项目
        run: npm run build
        working-directory: glancy-site
      - name: 清理服务器目录
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: rm -rf ${{ secrets.DEPLOY_PATH }}/*
      - name: 同步到服务器
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "glancy-site/dist/*"
          target: ${{ secrets.DEPLOY_PATH }}

