spring:
  application:
    name: glancy
  messages:
    basename: messages
  mail:
    host: smtpdm.aliyun.com
    port: 465
    username: no-reply@mail.glancy.xyz
    password: ${GLANCY_SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  datasource:
    url: jdbc:mysql://localhost:3306/glancy_db?useSSL=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: glancy_user
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        "[format_sql]": true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  web:
    resources:
      add-mappings: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

  logging:
    level:
      "[org.springframework.security]": DEBUG
      "[com.glancy.backend]": DEBUG
      "[org.springframework.web]": INFO

search:
  limit:
    nonMember: 10

llm:
  default-client: doubao
  temperature: 0.7
  prompt-path: prompts/english_to_chinese.txt

thirdparty:
  doubao:
    base-url: https://ark.cn-beijing.volces.com
    chat-path: /api/v3/chat/completions
    api-key: ""
oss:
  endpoint: https://oss-cn-beijing.aliyuncs.com
  bucket: glancy-avatar-bucket
  avatar-dir: avatars/
  public-read: true
  signed-url-expiration-minutes: 10080
  verify-location: true
  access-key-id: ${OSS_ACCESS_KEY_ID:}
  access-key-secret: ${OSS_ACCESS_KEY_SECRET:}
  security-token: ${OSS_SECURITY_TOKEN:}

tts:
  volcengine:
    # Credentials and routing for Volcengine TTS service.
    app-id: ${VOLCENGINE_APP_ID:}
    # Access token issued by Volcengine for authentication.
    access-token: ${VOLCENGINE_ACCESS_TOKEN:}
    cluster: volcano_tts
    # Base URL of Volcengine TTS endpoint. Override for staging or mocks.
    api-url: https://openspeech.bytedance.com/api/v1/tts
    # Interval for proactive health checks to Volcengine TTS.
    health-interval: PT10M

mail:
  verification:
    from: no-reply@mail.glancy.xyz
    sender:
      display-name: "Glancy 官方服务团队"
      reply-to: support@mail.glancy.xyz
    compliance:
      company-name: "Glancy 科技有限公司"
      company-address: "北京市朝阳区示例路 100 号 18 层"
      support-email: support@mail.glancy.xyz
      website: https://www.glancy.xyz
      unsubscribe-url: https://www.glancy.xyz/email/unsubscribe
      unsubscribe-mailto: unsubscribe@mail.glancy.xyz
    deliverability:
      feedback-id-prefix: glancy-txn
      entity-ref-id-prefix: glancy-verification
    code-length: 6
    ttl: PT10M
    templates:
      register:
        subject: "Glancy 注册验证码"
        body: "您的注册验证码为 {{code}}，请在 {{ttlMinutes}} 分钟内完成验证。"
      login:
        subject: "Glancy 登录验证码"
        body: "您的登录验证码为 {{code}}，请在 {{ttlMinutes}} 分钟内完成登录。"
