spring:
  application:
    name: glancy
  messages:
    basename: messages
  mail:
    host: smtpdm.aliyun.com
    port: 465
    username: no-reply@mail.glancy.xyz
    password: ${GLANCY_SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  datasource:
    url: jdbc:mysql://localhost:3306/glancy_db?useSSL=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: glancy_user
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        "[format_sql]": true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  web:
    resources:
      add-mappings: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

  logging:
    level:
      "[org.springframework.security]": DEBUG
      "[com.glancy.backend]": DEBUG
      "[org.springframework.web]": INFO

search:
  limit:
    nonMember: 10

llm:
  default-client: doubao
  temperature: 0.7
  prompt-path: prompts/english_to_chinese.txt
  prompt-paths:
    ENGLISH: prompts/english_to_chinese.txt
    CHINESE: prompts/chinese_to_chinese.txt

gomemo:
  default-daily-target: 12
  search-history-window: 80
  plan-oversampling-factor: 2
  completion-retention-threshold: 70
  scoring:
    base-score: 2
    recency-weight: 6
    favorite-bonus: 12
    interest-weight: 5
    goal-weight: 4
    future-plan-weight: 4
    frequency-weight: 3
    age-length-penalty: 1
  review:
    prompt-path: prompts/gomemo_review.txt
    temperature: 0.55
    client: doubao
  mode-catalog:
    CARD:
      title: "沉浸式卡片"
      description: "图文助记并行，帮助快速建立记忆框架。"
      focus: "先回顾释义，再口述自己的理解。"
    MULTIPLE_CHOICE:
      title: "智适应选择题"
      description: "围绕同义、反义词动态生成干扰项。"
      focus: "分析每个选项与语境的差异。"
    SPELLING:
      title: "精准拼写"
      description: "拆分音节与重音，引导形成肌肉记忆。"
      focus: "用手写或键入逐字拼写，复盘错误位置。"
    VISUAL_ASSOCIATION:
      title: "图像联想"
      description: "结合兴趣与目标场景挑选视觉锚点。"
      focus: "为单词匹配一个与你目标最贴近的画面。"
    LISTENING:
      title: "沉浸听力"
      description: "高保真音频与跟读反馈同步呈现。"
      focus: "循环跟读直至语流顺滑。"

thirdparty:
  doubao:
    base-url: https://ark.cn-beijing.volces.com
    chat-path: /api/v3/chat/completions
    api-key: ""
    max-completion-tokens: 20480
oss:
  endpoint: https://oss-cn-beijing.aliyuncs.com
  bucket: glancy-avatar-bucket
  avatar-dir: avatars/
  public-read: true
  signed-url-expiration-minutes: 10080
  verify-location: true
  access-key-id: ${OSS_ACCESS_KEY_ID:}
  access-key-secret: ${OSS_ACCESS_KEY_SECRET:}
  security-token: ${OSS_SECURITY_TOKEN:}

tts:
  volcengine:
    # Credentials and routing for Volcengine TTS service.
    app-id: ${VOLCENGINE_APP_ID:}
    # Access token issued by Volcengine for authentication.
    access-token: ${VOLCENGINE_ACCESS_TOKEN:}
    cluster: volcano_tts
    # Base URL of Volcengine TTS endpoint. Override for staging or mocks.
    api-url: https://openspeech.bytedance.com/api/v1/tts
    # Interval for proactive health checks to Volcengine TTS.
    health-interval: PT10M

mail:
  verification:
    from: no-reply@mail.glancy.xyz
    sender:
      display-name: "Glancy 官方服务团队"
      reply-to: support@mail.glancy.xyz
    compliance:
      company-name: "Glancy 科技有限公司"
      company-address: "北京市朝阳区示例路 100 号 18 层"
      support-email: support@mail.glancy.xyz
      website: https://www.glancy.xyz
      unsubscribe-url: https://www.glancy.xyz/email/unsubscribe
      unsubscribe-mailto: unsubscribe@mail.glancy.xyz
    deliverability:
      feedback-id-prefix: glancy-txn
      entity-ref-id-prefix: glancy-verification
      mailbox-provider-policies:
        icloud:
          domains:
            - icloud.com
            - me.com
            - mac.com
          list-id: "Glancy 事务通知 <mail.glancy.xyz>"
          complaints-mailto: complaints@mail.glancy.xyz
          enforce-list-unsubscribe: true
    infrastructure:
      reverse-dns-domain: mail.glancy.xyz
      spf-record: "v=spf1 include:spf.mail.glancy.xyz ~all"
      dkim-selector: default
      dmarc-policy: "v=DMARC1; p=quarantine; rua=mailto:dmarc@mail.glancy.xyz"
      arc-seal-enabled: true
      arc-authentication-results: "i=1; mx.glancy.xyz; dkim=pass header.i=@mail.glancy.xyz; spf=pass smtp.mailfrom=no-reply@mail.glancy.xyz"
      arc-message-signature: "i=1; a=rsa-sha256; c=relaxed/relaxed; d=mail.glancy.xyz; s=arc; bh=hash; b=signature"
      arc-seal: "i=1; s=arc; d=mail.glancy.xyz; cv=none; b=seal"
    audience-policy:
      inactivity-threshold: P180D
      soft-bounce-suppression-threshold: 3
      hard-bounce-suppression-threshold: 1
    streams:
      transactional-domain: mail.glancy.xyz
      transactional-ip-pool: ip-pool-txn
      marketing-domain: marketing.glancy.xyz
      marketing-ip-pool: ip-pool-mkt
    code-length: 6
    ttl: PT10M
    templates:
      register:
        subject: "Glancy 注册验证码"
        body: "您的注册验证码为 {{code}}，请在 {{ttlMinutes}} 分钟内完成验证。"
      login:
        subject: "Glancy 登录验证码"
        body: "您的登录验证码为 {{code}}，请在 {{ttlMinutes}} 分钟内完成登录。"
      change_email:
        subject: "Glancy 邮箱换绑验证码"
        body: "您的邮箱换绑验证码为 {{code}}，请在 {{ttlMinutes}} 分钟内完成验证。"
