voices:
  zh-CN:
    default: zh_female_cancan_mars_bigtts
    options:
      - id: zh_female_cancan_mars_bigtts
        label: "CanCan·女声"
        plan: all
  en-US:
    default: en_male_corey_emo_v2_mars_bigtts
    options:
      - id: en_male_corey_emo_v2_mars_bigtts
        label: "Corey·男声"
        plan: all
      - id: en_female_nadia_tips_emo_v2_mars_bigtts
        label: "Nadia·女声"
        plan: pro
features:
  hotReload: true
  useCdn: true
  returnUrl: true
  countCachedAsUsage: false
