name: Deploy Website

on:
  push:
    branches: [main, 'feature-*']
    paths:
      - 'website/glancy-website/**'
  workflow_dispatch: {}

concurrency:
  group: website-deploy
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    # 所有 run 步骤默认在前端目录执行（字面值，不能用表达式）
    defaults:
      run:
        working-directory: website/glancy-website

    steps:
      - uses: actions/checkout@v4

      - name: Preflight - 目录与文件健全性检查
        run: |
          set -euxo pipefail
          pwd
          test -d . && test -f package.json && test -f vite.config.js

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Lint
        run: |
          npm run lint
          npm run lint:css

      - name: Build
        run: npm run build

      - name: Prepare remote dist dir
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            set -euxo pipefail
            sudo mkdir -p /var/www/glancy-website/dist
            sudo chown -R $USER:$USER /var/www/glancy-website
            rm -rf /var/www/glancy-website/dist/*

      - name: Upload dist
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          # 这里是相对“仓库根”的路径，不能写成 ./dist/**
          source: 'website/glancy-website/dist/**'
          target: '/var/www/glancy-website/dist/'

      - name: Verify remote files
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            set -euxo pipefail
            ls -lah /var/www/glancy-website/dist
            test -f /var/www/glancy-website/dist/index.html