name: Update Error Page

on:
    workflow_dispatch:

jobs:
    upload_error:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Upload error page
              uses: appleboy/scp-action@v0.1.4
              with:
                  host: ${{ secrets.DEPLOY_HOST }}
                  username: ${{ secrets.DEPLOY_USER }}
                  key: ${{ secrets.DEPLOY_KEY }}
                  source: website/glancy-site/public/error.html
                  target: ${{ secrets.DEPLOY_PATH }}
