name: Deploy Website

on:
  push:
    branches: [main, 'feature-*']
    paths:
      - 'website/glancy-website/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      WEBSITE_DIR: ${{ github.workspace }}/website/glancy-website
      TARGET_DIR: ${{ secrets.WEBSITE_DEPLOY_PATH }}glancy-website/dist
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.WEBSITE_DIR }}

      - name: Lint code
        run: |
          npm run lint
          npm run lint:css
        working-directory: ${{ env.WEBSITE_DIR }}

      - name: Build project
        run: npm run build
        working-directory: ${{ env.WEBSITE_DIR }}

      # 仅创建/清空目标 dist 目录，别再删整个 /var/www
      - name: Prepare remote dir
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            mkdir -p ${{ env.TARGET_DIR }}
            rm -rf ${{ env.TARGET_DIR }}/*

      # 把本地 dist 内容上传到远端 dist 目录
      - name: Sync dist to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: 'website/glancy-website/dist/**'
          target: ${{ env.TARGET_DIR }}/

      # 可选：上线后核对一下
      - name: Verify remote files
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            ls -lah ${{ env.TARGET_DIR }}
            test -f ${{ env.TARGET_DIR }}/index.html