name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Code style check
        run: ./mvnw -B spotless:check checkstyle:check
        working-directory: backend
      - name: Build project
        run: ./mvnw -B clean package -DskipTests
        working-directory: backend
      - name: Upload jar to server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          timeout: 2m
          source: backend/target/glancy-backend.jar
          target: ${{ secrets.BACKEND_DEPLOY_PATH }}/target/
          overwrite: true
          strip_components: 1
          debug: true
      - name: Upload service unit
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          timeout: 2m
          source: backend/scripts/glancy-backend.service
          target: ${{ secrets.BACKEND_DEPLOY_PATH }}/
          overwrite: true
          strip_components: 1
          debug: true
      - name: Restart service
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            sudo cp ${{ secrets.BACKEND_DEPLOY_PATH }}/glancy-backend.service /etc/systemd/system/glancy-backend.service
            sudo systemctl daemon-reload
            if sudo systemctl list-units --type=service --all | grep -q 'glancy-backend.service'; then
              sudo systemctl restart glancy-backend.service
            else
              sudo systemctl enable --now glancy-backend.service
            fi
