name: Restart Backend

on:
  workflow_dispatch:

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - name: Restart backend service
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            sudo cp ${{ secrets.BACKEND_DEPLOY_PATH }}/glancy-backend.service /etc/systemd/system/glancy-backend.service
            sudo systemctl daemon-reload
            if sudo systemctl list-units --type=service --all | grep -q 'glancy-backend.service'; then
              sudo systemctl restart glancy-backend.service
            else
              sudo systemctl enable --now glancy-backend.service
            fi
